{% set name = "Bootstrap-Flask" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 8dcd6d6ed5458cfb76da4d57d2277f447da08d7977d551c82f51919f62c9586c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
  run:
    - flask
    - python >={{ python_min }}
    - wtforms

test:
  imports:
    - flask_bootstrap
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://bootstrap-flask.readthedocs.io
  summary: 'Bootstrap 4 & 5 helper for your Flask projects.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://bootstrap-flask.readthedocs.io
  dev_url: https://github.com/helloflask/bootstrap-flask

extra:
  recipe-maintainers:
    - m-rossi
