{% set name = "Bootstrap-Flask" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f7aa1b8be31e182fa2eaff2580e9b66aa9fad14f1a35e5c03d486169fb6c1a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0
  run:
    - flask
    - python >=3.8
    - wtforms

test:
  imports:
    - flask_bootstrap
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://bootstrap-flask.readthedocs.io
  summary: 'Bootstrap 4 & 5 helper for your Flask projects.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://bootstrap-flask.readthedocs.io
  dev_url: https://github.com/helloflask/bootstrap-flask

extra:
  recipe-maintainers:
    - m-rossi
